set(GAME_DEFINES
    CSTRIKE_DLL NEXT_BOT
)
set(GAME_INCLUDES
    ${SRCDIR}/game/shared/cstrike
    cstrike/VGUI
    cstrike
)
list(REMOVE_ITEM SOURCES ${SRCDIR}/game/shared/weapon_parse_default.cpp)
list(APPEND SOURCES
    cstrike/cs_replay.cpp

    c_team_objectiveresource.cpp
	c_team_train_watcher.cpp
	hud_base_account.cpp
	hud_voicestatus.cpp
	hud_baseachievement_tracker.cpp
	${SRCDIR}/game/client/hud_vote.cpp
	${SRCDIR}/game/shared/predicted_viewmodel.cpp
# CounterStrike DLL
	${SRCDIR}/game/shared/cs_achievements_and_stats_interface.cpp
	${SRCDIR}/game/shared/cstrike/achievements_cs.cpp
	${SRCDIR}/game/shared/cstrike/basecsgrenade_projectile.cpp
	cstrike/buy_presets/buy_preset.cpp
	cstrike/buy_presets/buy_preset_debug.cpp
	cstrike/buy_presets/buy_preset_weapon_info.cpp
	cstrike/buy_presets/buy_presets.cpp
	cstrike/c_cs_hostage.cpp
	cstrike/c_cs_player.cpp
	cstrike/c_cs_playerresource.cpp
	cstrike/c_cs_team.cpp
	cstrike/c_csrootpanel.cpp
	cstrike/c_plantedc4.cpp
	cstrike/c_te_radioicon.cpp
	cstrike/c_te_shotgun_shot.cpp
	cstrike/clientmode_csnormal.cpp
	${SRCDIR}/game/shared/cstrike/cs_ammodef.cpp
	${SRCDIR}/game/shared/cstrike/cs_gamemovement.cpp
	${SRCDIR}/game/shared/cstrike/cs_gamerules.cpp
	${SRCDIR}/game/shared/cstrike/cs_gamestats_shared.cpp
	${SRCDIR}/game/shared/steamworks_gamestats.cpp
	cstrike/cs_in_main.cpp
	${SRCDIR}/game/shared/cstrike/cs_player_shared.cpp
	${SRCDIR}/game/shared/cstrike/cs_playeranimstate.cpp
	cstrike/cs_prediction.cpp
	${SRCDIR}/game/shared/cstrike/cs_shareddefs.cpp
	cstrike/cs_client_gamestats.cpp
	${SRCDIR}/game/shared/cstrike/cs_usermessages.cpp
	cstrike/cs_view_scene.cpp
	${SRCDIR}/game/shared/cstrike/cs_weapon_parse.cpp
	cstrike/fx_cs_blood.cpp
	cstrike/fx_cs_impacts.cpp
	cstrike/fx_cs_knifeslash.cpp
	cstrike/fx_cs_muzzleflash.cpp
	${SRCDIR}/game/shared/cstrike/fx_cs_shared.cpp
	cstrike/fx_cs_weaponfx.cpp
	${SRCDIR}/game/shared/cstrike/bot/shared_util.cpp
	cstrike/vgui_rootpanel_cs.cpp
# HUD Elements
    cstrike/cs_hud_ammo.cpp
	cstrike/cs_hud_chat.cpp
	cstrike/cs_hud_damageindicator.cpp
	cstrike/cs_hud_freezepanel.cpp
	cstrike/cs_hud_playerhealth.cpp
	cstrike/cs_hud_health.cpp
	cstrike/cs_hud_scope.cpp
	cstrike/cs_hud_target_id.cpp
	cstrike/cs_hud_weaponselection.cpp
	cstrike/hud_account.cpp
	cstrike/hud_armor.cpp
	cstrike/hud_c4.cpp
	cstrike/hud_deathnotice.cpp
	cstrike/hud_defuser.cpp
	cstrike/hud_flashbang.cpp
	cstrike/hud_hostagerescue.cpp
	cstrike/hud_progressbar.cpp
	cstrike/hud_radar.cpp
	cstrike/hud_roundtimer.cpp
	cstrike/hud_scenarioicon.cpp
	cstrike/hud_shopping_cart.cpp
	cstrike/cs_hud_achievement_announce.cpp
	cstrike/cs_hud_achievement_tracker.cpp
	cstrike/radio_status.cpp
# Weapon
    ${SRCDIR}/game/shared/cstrike/weapon_ak47.cpp
	${SRCDIR}/game/shared/cstrike/weapon_aug.cpp
	${SRCDIR}/game/shared/cstrike/weapon_awp.cpp
	${SRCDIR}/game/shared/cstrike/weapon_basecsgrenade.cpp
	${SRCDIR}/game/shared/cstrike/weapon_c4.cpp
	${SRCDIR}/game/shared/cstrike/weapon_csbase.cpp
	${SRCDIR}/game/shared/cstrike/weapon_csbasegun.cpp
	${SRCDIR}/game/shared/cstrike/weapon_deagle.cpp
	${SRCDIR}/game/shared/cstrike/weapon_elite.cpp
	${SRCDIR}/game/shared/cstrike/weapon_famas.cpp
	${SRCDIR}/game/shared/cstrike/weapon_fiveseven.cpp
	${SRCDIR}/game/shared/cstrike/weapon_flashbang.cpp
	${SRCDIR}/game/shared/cstrike/weapon_g3sg1.cpp
	${SRCDIR}/game/shared/cstrike/weapon_galil.cpp
	${SRCDIR}/game/shared/cstrike/weapon_glock.cpp
	${SRCDIR}/game/shared/cstrike/weapon_hegrenade.cpp
	${SRCDIR}/game/shared/cstrike/weapon_knife.cpp
	${SRCDIR}/game/shared/cstrike/weapon_m249.cpp
	${SRCDIR}/game/shared/cstrike/weapon_m3.cpp
	${SRCDIR}/game/shared/cstrike/weapon_m4a1.cpp
	${SRCDIR}/game/shared/cstrike/weapon_mac10.cpp
	${SRCDIR}/game/shared/cstrike/weapon_mp5navy.cpp
	${SRCDIR}/game/shared/cstrike/weapon_p228.cpp
	${SRCDIR}/game/shared/cstrike/weapon_p90.cpp
	${SRCDIR}/game/shared/cstrike/weapon_scout.cpp
	${SRCDIR}/game/shared/cstrike/weapon_sg550.cpp
	${SRCDIR}/game/shared/cstrike/weapon_sg552.cpp
	${SRCDIR}/game/shared/cstrike/weapon_smokegrenade.cpp
	${SRCDIR}/game/shared/cstrike/weapon_tmp.cpp
	${SRCDIR}/game/shared/cstrike/weapon_ump45.cpp
	${SRCDIR}/game/shared/cstrike/weapon_usp.cpp
	${SRCDIR}/game/shared/cstrike/weapon_xm1014.cpp
# vgui
    cstrike/VGUI/achievement_stats_summary.cpp
	cstrike/VGUI/achievements_page.cpp
	cstrike/VGUI/stats_summary.cpp
	cstrike/VGUI/stat_card.cpp
	cstrike/VGUI/base_stats_page.cpp
	cstrike/VGUI/match_stats_page.cpp
	cstrike/VGUI/lifetime_stats_page.cpp
	cstrike/VGUI/bordered_panel.cpp
	cstrike/VGUI/backgroundpanel.cpp
	cstrike/VGUI/buypreset_imageinfo.cpp
	cstrike/VGUI/buypreset_listbox.cpp
	cstrike/VGUI/buypreset_panel.cpp
	cstrike/VGUI/career_box.cpp
	cstrike/VGUI/career_button.cpp
	cstrike/VGUI/counterstrikeviewport.cpp
	cstrike/VGUI/cstrikebuyequipmenu.cpp
	cstrike/VGUI/cstrikebuymenu.cpp
	cstrike/VGUI/cstrikeclassmenu.cpp
	cstrike/VGUI/cstrikeclientscoreboard.cpp
	cstrike/VGUI/cstrikespectatorgui.cpp
	cstrike/VGUI/cstriketeammenu.cpp
	cstrike/VGUI/cstriketextwindow.cpp
	cstrike/vgui_c4panel.cpp
	cstrike/vgui_viewc4panel.cpp
	cstrike/VGUI/win_panel_round.cpp
# NextBot
    NextBot/C_NextBot.cpp
# game_controls
    game_controls/buymenu.cpp
	game_controls/buysubmenu.cpp
	game_controls/classmenu.cpp
)